/**
 * @file pch.cpp
 * @brief Stores Resource when the app run
 * @author Ecofloc's Team
 * @date 2025-02-03
 */

//{{NO_DEPENDENCIES}}
// Include file generated by Microsoft Visual C++.
// Used by app.rc
